;; This logfile was generated automatically by `xindy'
;; at 18.04.2016  12:07:40
;; Indexstyle: "/tmp/CaYO6gHJp8", Rawindex: "/tmp/yRK6CZz1EQ", Output: "main.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "†Ã€È" -> "C"
Letter-group: "»ÊÚÚ" -> "M"
Letter-group: "6´ÃæÈ€¼" -> "glsnumbers"
Letter-group: "„´—" -> "B"
Letter-group: "ÐÈ¨" -> "S"
Letter-group: "¨2†" -> "I"
Letter-group: "¼Ð" -> "D"
Letter-group: "à¨" -> "G"
Letter-group: "¤†¨" -> "H"
Letter-group: "¨—" -> "I"
Letter-group: "¨ÃÚ" -> "I"
Letter-group: "¨Èå4" -> "I"
Letter-group: "¨Èå6" -> "I"
Letter-group: "´€¼" -> "L"
Letter-group: "»2»" -> "M"
Letter-group: "¼Ú¼à" -> "N"
Letter-group: "È€¼" -> "P"
Letter-group: "¨†»È" -> "I"
Letter-group: "ÃÐ" -> "O"
Letter-group: "ÚœÚÈ" -> "T"
Letter-group: "àÈ" -> "U"
Letter-group: "Ú†È" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "6´ÃæÈ€¼" -> "glsnumbers"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "„´—" -> "B"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†Ã€È" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ð" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "à¨" -> "G"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤†¨" -> "H"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨2†" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´€¼" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»2»" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¼Ú¼à" -> "N"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÃÐ" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È€¼" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÈ¨" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ú†È" -> "T"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "àÈ" -> "U"
WARNING: location-reference "{}{x}" did match multiple location-classes! (taking first one)
